banner:
  enable: true
  title: è¸ç€æ¢¦èµ°è¿‡æ—¶å…‰
  border: true
  cloud:
    enable: true
    color: black
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

notice:
  enable: true
  content: æ¬¢è¿å…‰ä¸´æˆ‘çš„åšå®¢
bg_image:
  enable: true
  url: /images/light.jpg
  dark: /images/banner.jpg
  # blur: 10px # è®¾ç½®èƒŒæ™¯æ¨¡ç³Šç¨‹åº¦
  # opacity: 0.6

medium_zoom: true

avatar:
  enable: true
  url: /images/AgonySec.jpg
  rounded: true
  opacity: 1
  mickey_mouse: false
  status:
    enable: true
    emoji: ğŸ˜­
    message: æ‚Ÿå·²å¾€ä¹‹ä¸è°ï¼ŒçŸ¥æ¥è€…ä¹‹å¯è¿½ã€‚

sidebar:
  # bg_image: ### 
  bg_position: bottom 3rem center
  tagcloud:
    enable: false
    amount: 20

social:
  - name: GitHub
    link: https://github.com/AgonySec
    icon: ri:github-line
    color: '#181717'
  - name: E-Mail
    link: mailto:chenyuanhang2022@outlook.com
    icon: ri:mail-line
    color: '#8E71C1'
  # - name: å¾®åš
  #   link: #
  #   icon: ri:weibo-line
  #   color: '#E6162D'
  # - name: è±†ç“£
  #   link: #
  #   icon: ri:douban-line
  #   color: '#007722'
  # - name: ç½‘æ˜“äº‘éŸ³ä¹
  #   link: https://music.163.com/#/user/home?id=1485292158
  #   icon: ri:netease-cloud-music-line
  #   color: '#C10D0C'
  # - name: çŸ¥ä¹
  #   link: https://www.zhihu.com/people/yemengstar
  #   icon: ri:zhihu-line
  #   color: '#0084FF'
  # - name: å“”å“©å“”å“©
  #   link: https://space.bilibili.com/1951763981
  #   icon: ri:bilibili-line
  #   color: '#FF8EB3'
  # - name: å¾®ä¿¡å…¬ä¼—å·
  #   link: #
  #   icon: ri:wechat-2-line
  #   color: '#1AAD19'

footer:
  since: 2024 # èµ·å§‹å¹´ä»½
  # icon:
  #   name: ri:cloud-line
  #   animated: true
  #   color: '#0078E7'
  #   url: ä½ çš„é“¾æ¥
  #   title: è‡ªæ‹Ÿ
  powered:
    enable: false # æ˜¯å¦æ˜¾ç¤ºä¸»é¢˜åç§°
  # beian:
  #   enable: true # æ˜¯å¦æ˜¾ç¤ºå¤‡æ¡ˆ
  #   # ICPå¤‡æ¡ˆ
  #   icp: è‹ICPå¤‡xxxxxxxxxxå·
  #   # å…¬å®‰å¤‡æ¡ˆ
  #   gongan:
  #     enable: true
  #     text: è‹å…¬ç½‘å®‰å¤‡XXXXXXXXå·
  #     id: XXXXXXXX
 
  live_time: # è¿è¡Œæ—¶é—´
    enable: true
    prefix: æ„Ÿè°¢é™ªä¼´
    suffix: (â—'â—¡'â—)
    start_time: '2024-10-02T00:00:00' # å¼€å§‹æ—¶é—´

